### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by datafilter** [awesome-club/not-a-framework#1]
Thanks for sharing, this is awesome :)

To make it easier for others to contribute it would help if there were:
* A [license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#disclaimer) eg Unlicense, MIT or CC-zero
* If you include a similar example/demo you used in the video, even if there is no actual back-end to support it, it shows how to use the framework.

Thanks for the YT channel, long time subscriber here. Something adjacent to/for this that might interest you is keeping state in data-attributes instead of classes:
https://www.30secondsofcode.org/html/s/data-attributes-as-state/
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset

**Comment by awesome-club** [comment]
Thanks for reaching out!
The licence is added together with a very basic Readme - I'll make some slight adjustments in the next few days.

Thanks for the `dataset` suggestion - it might come in handy since I'll need to mark DOM elements for caching & cleanup purposes.
