### ISSUE TITLE
Error caused by Inconsistent use of attr and evtName in event handling

### ISSUE THREAD

**Issue by redomar** [awesome-club/not-a-framework#4]
In the event handling code within `main.js`, there is an inconsistency in the use of `attr` and `evtName`. In some cases, `attr` is used where `evtName` should be used. This inconsistency lead to error on my browser ~as `attr` might not always hold the correct event name.~ `attr` doesn't seem to be declared

<img width="284" alt="image" src="https://github.com/awesome-club/not-a-framework/assets/2476381/a7e9d9bf-ee28-43ee-9138-75ed627eabec">

**Comment by redomar** [comment]
Working on a pull request

**Comment by awesome-club** [comment]
@redomar thank you for pointing this out. I was just working on some cleanup and fixing this as well.

Fixed in https://github.com/awesome-club/not-a-framework/commit/55664eeeedf55b8b6834624e16f5c546931d115b

**Comment by redomar** [comment]
That's great, Thanks for the update
