### ISSUE TITLE
Suggestion: Convert Go demo to JS

### ISSUE THREAD

**Issue by joeleisner** [awesome-club/not-a-framework#7]
Would you be opposed to converting the Go demo to JS? It would reduce the number of required system dependencies to get up and running with the project, and it could be hooked into the package scripts along side `npm run build`.

I've been experimenting with a [Hono](https://hono.dev/) conversion on a local branch, and it's structurally one-to-one compared to the Go demo. I'd be happy to submit a pull request if you're open to it.

Let me know what you think!

**Comment by awesome-club** [comment]
@joeleisner this sounds like a great idea!
I'm thinking we can add multiple examples in the `demo` folder, so feel free to create a `hono-counter` (or any name you see fit) under `demo` and I'll be glad to merge your PR.
Thank you for your time on this one!

**Comment by joeleisner** [comment]
@awesome-club I've submitted my PR for this! Some things to note:

1. The Hono demo runs on port 8001 as to not conflict with the Go demo, just in case.
2. The Hono demo can be run via `npm run demo`. I assume in the future, there will be more diverse demos, so this can be updated to be more specific in the future.

Let me know if you have any questions, concerns, or suggested changes!

**Comment by awesome-club** [comment]
@joeleisner looks great!
Thank you again for your effort on this!

**Comment by joeleisner** [comment]
@awesome-club Awesome! You're welcome.
